openapi: 3.0.0
info:
  title: Sample API
  version: 1.0.0


servers:
  - url: /api

components:
  responses:
    JsonValidationError:
      description: Invalid data
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: The given data was invalid
              errors:
                type: object
                properties:
                  field_name:
                    type: array
                    items:
                      type: string
                      example: Attribute field_name is required.
    JsonNotFoundError:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                example: Not Found

  securitySchemes:
    Bearer:
      type: http
      scheme: bearer

  schemas:
    User:
      $ref: schemas/user.yaml#/User
    Transaction:
      $ref: schemas/transaction.yaml#/Transaction
    Balance:
      $ref: schemas/balance.yaml#/Balance

paths:
  /auth/login:
    $ref: paths/auth.yaml#/login
  /auth/user:
    $ref: paths/auth.yaml#/user
  /auth/logout:
    $ref: paths/auth.yaml#/logout
  /user/register:
    $ref: paths/user.yaml#/register
  /user/balances:
    $ref: paths/user.yaml#/balances
  /transactions:
    $ref: paths/transactions.yaml#/transactions
